### PR TITLE
add readme

### PR DESCRIPTION
**Pull request by royr5**

### CODE REVIEW

**Review by karobarari — APPROVED** [review]
thanks roshan for both front and back readmes

**Review by karobarari — COMMENTED** [review]
I'm trying to figure out what is wrong with the test that is not passing

**Comment by royr5** [comment]
> I'm trying to figure out what is wrong with the test that is not passing
> 
> 

I don't have the environment variables for mongodb

**Comment by karobarari** [comment]
I've got one in name of Francesco I'll send you in discord

**Review by Jord000 — COMMENTED** [review]
Maybe needs a little intro like you have on frontend to show what the intention of the repo is. 

eg - 
This repository builds a RESTful API and databases, to allow the WAX music review app to access music, user data and reviews. Relational data is stored on a PostgreSQL database, while non-relational user data is stored securely on MongoDB Atlas.

**Pull request closed without merging**
